# Generated by Django 2.2 on 2020-04-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0002_auto_20200310_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('Q1', models.CharField(max_length=200)),
                ('Q2', models.CharField(max_length=200)),
                ('Q3', models.CharField(max_length=200)),
                ('Q4', models.CharField(max_length=200)),
                ('Q5', models.CharField(max_length=200)),
                ('Q6', models.CharField(max_length=200)),
                ('Q7', models.CharField(max_length=200)),
                ('Q8', models.CharField(max_length=200)),
                ('Q9', models.CharField(max_length=200)),
                ('Q10', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Per',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_namep', models.CharField(max_length=200)),
                ('Q1p', models.CharField(max_length=200)),
                ('Q2p', models.CharField(max_length=200)),
                ('Q3p', models.CharField(max_length=200)),
                ('Q4p', models.CharField(max_length=200)),
                ('Q5p', models.CharField(max_length=200)),
                ('Q6p', models.CharField(max_length=200)),
                ('Q7p', models.CharField(max_length=200)),
                ('Q8p', models.CharField(max_length=200)),
                ('Q9p', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Dt',
        ),
    ]
